"""add role to users

Revision ID: 051076b0d327
Revises: e5b1e59edad6
Create Date: 2026-09-22 14:39:14.356908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '051076b0d327'
down_revision: Union[str, Sequence[str], None] = 'e5b1e59edad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    userrole_enum = sa.Enum('EMPLOYER','JOB_SEEKER', name='userrole')
    userrole_enum.create(op.get_bind(),checkfirst=True)
    op.add_column('users', sa.Column('role', userrole_enum, nullable=False,server_default='JOB_SEEKER',),)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    sa.Enum(name='userrole').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
